In [2]:
import pandas as pd

In [3]:
# read the Dataset mental_wellness_train.csv(archive (3))
df01 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\archive (3)\\mental_wellness_train.csv")
# read the Dataset mental_wellness_tracker.csv(archive (3))
df02 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\archive (3)\\mental_wellness_tracker.csv")
# read the Dataset mental_wellness_test.csv(archive (3))
df03 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\archive (3)\\mental_wellness_test.csv")

In [4]:
print(df01.shape)
print(df02.shape)
print(df03.shape)

(1200, 12)
(1500, 12)
(300, 12)

In [5]:
df01.head()

,User_ID,Date,Mood_Score,Sleep_Hours,Sleep_Quality,Screen_Time_Hours,Physical_Activity_Min,Social_Interaction_Hours,Work_Productivity_Score,Weather,Diet_Quality,Stress_Level
0,U038,2023-06-07,7,10.0,Excellent,5.1,41,1.8,10,Sunny,Good,3
1,U046,2023-06-19,2,5.7,Good,5.5,36,0.9,3,Sunny,Good,8
2,U015,2023-06-03,3,7.5,Good,1.0,7,6.6,3,Cloudy,Good,8
3,U014,2023-06-24,4,5.6,Good,3.7,35,1.3,4,Rainy,Average,5
4,U016,2023-06-02,10,7.3,Excellent,5.4,29,3.6,10,Sunny,Average,1

In [6]:
df02.head()

,User_ID,Date,Mood_Score,Sleep_Hours,Sleep_Quality,Screen_Time_Hours,Physical_Activity_Min,Social_Interaction_Hours,Work_Productivity_Score,Weather,Diet_Quality,Stress_Level
0,U001,2023-06-01,5,8.5,Fair,10.0,14,1.1,6,Rainy,Poor,5
1,U001,2023-06-02,6,8.0,Good,4.8,0,3.4,6,Cloudy,Average,4
2,U001,2023-06-03,7,7.4,Good,3.5,38,2.3,8,Cloudy,Good,6
3,U001,2023-06-04,3,7.9,Fair,4.5,46,0.9,5,Rainy,Average,7
4,U001,2023-06-05,4,6.9,Good,2.5,7,0.0,4,Cloudy,Good,7

In [7]:
df03.head()

,User_ID,Date,Mood_Score,Sleep_Hours,Sleep_Quality,Screen_Time_Hours,Physical_Activity_Min,Social_Interaction_Hours,Work_Productivity_Score,Weather,Diet_Quality,Stress_Level
0,U001,2023-06-02,6,8.0,Good,4.8,0,3.4,6,Cloudy,Average,4
1,U001,2023-06-09,4,10.0,Excellent,4.0,39,3.4,7,Sunny,Average,6
2,U001,2023-06-14,8,6.5,Fair,4.4,34,1.4,9,Sunny,Good,1
3,U001,2023-06-15,10,8.0,Fair,4.0,62,0.0,10,Cloudy,Poor,1
4,U001,2023-06-21,6,7.2,Poor,4.5,14,1.7,7,Sunny,Good,4

In [8]:
df0 = pd.concat([df01, df02, df03], axis=0)

In [9]:
df0.shape

(3000, 12)

In [10]:
df0 = df0.drop_duplicates()

In [11]:
df0.shape

(1500, 12)

In [12]:
df0.head()

,User_ID,Date,Mood_Score,Sleep_Hours,Sleep_Quality,Screen_Time_Hours,Physical_Activity_Min,Social_Interaction_Hours,Work_Productivity_Score,Weather,Diet_Quality,Stress_Level
0,U038,2023-06-07,7,10.0,Excellent,5.1,41,1.8,10,Sunny,Good,3
1,U046,2023-06-19,2,5.7,Good,5.5,36,0.9,3,Sunny,Good,8
2,U015,2023-06-03,3,7.5,Good,1.0,7,6.6,3,Cloudy,Good,8
3,U014,2023-06-24,4,5.6,Good,3.7,35,1.3,4,Rainy,Average,5
4,U016,2023-06-02,10,7.3,Excellent,5.4,29,3.6,10,Sunny,Average,1

In [13]:
df0.columns

Index(['User_ID', 'Date', 'Mood_Score', 'Sleep_Hours', 'Sleep_Quality',
       'Screen_Time_Hours', 'Physical_Activity_Min',
       'Social_Interaction_Hours', 'Work_Productivity_Score', 'Weather',
       'Diet_Quality', 'Stress_Level'],
      dtype='object')

In [14]:
df = df0.drop(columns=['User_ID', 'Date', 'Mood_Score', 'Screen_Time_Hours',
    'Social_Interaction_Hours', 'Work_Productivity_Score', 'Weather',])

In [15]:
df.head()

   Sleep_Hours Sleep_Quality  Physical_Activity_Min Diet_Quality  Stress_Level
0         10.0     Excellent                     41         Good             3
1          5.7          Good                     36         Good             8
2          7.5          Good                      7         Good             8
3          5.6          Good                     35      Average             5
4          7.3     Excellent                     29      Average             1

In [16]:
df.columns

Index(['Sleep_Hours', 'Sleep_Quality', 'Physical_Activity_Min', 'Diet_Quality',
       'Stress_Level'],
      dtype='object')

In [17]:
df.to_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\Final Code\\Physical Information\\Mental Wellness\\mental_wellness.csv")