In [2]:
import pandas as pd

In [3]:
# read the student-mat.csv
df01 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\student-mat.csv", sep=';')
# read the student-por.csv
df02 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\student-por.csv", sep=';')

In [4]:
df01.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [5]:
df02.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [6]:
print(df01.shape)
print(df02.shape)

(395, 33)
(649, 33)

In [7]:
df0 = pd.concat([df01, df02],axis=0)

In [10]:
df0 = df0.drop_duplicates()
print(df0.shape)

(1044, 33)

In [11]:
df0.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [12]:
df = df0.drop(columns=['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
    'Mjob', 'Fjob', 'reason', 'guardian','nursery', 'higher', 'romantic', 'famrel', 'Dalc',
    'Walc', 'health', 'absences', 'G1', 'G2', 'G3'])

In [13]:
df.head()

,traveltime,studytime,failures,schoolsup,famsup,paid,activities,internet,freetime,goout
0,2,2,0,yes,no,no,no,no,3,4
1,1,2,0,no,yes,no,no,yes,3,3
2,1,2,3,yes,no,yes,no,yes,3,2
3,1,3,0,no,yes,yes,yes,yes,2,2
4,1,2,0,no,yes,yes,no,no,3,2

In [14]:
df.columns

Index(['traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid',
       'activities', 'internet', 'freetime', 'goout'],
      dtype='object')

In [15]:
df.to_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\Final Code\\Presonal Information\\Student Performance\\stu_perf.csv")